name: Formatting

on:
  push:
    branches: [master]
    paths:
      - docs/**
  pull_request:
    branches: [master]
    paths:
      - docs/**

jobs:
  test:
    name: Check docs formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check formatting
        uses: actionsx/prettier@v2
        with:
            args: --check docs
